#' Calculate confidence intervals for contrasts of interest from ANOVA models
#'
#' This function computes confidence intervals for contrasts testing effects
#' from ANOVA models. The method used to compute the confidence intervals
#' is selected by the user (see below). The methods are described in Bird
#' (2002) (see below) https://doi.org/10.1177/0013164402062002001
#'
#' # METHODS
#' ind - individual t ci's - A set of individual 100(1 - α)% confidence
#' intervals on planned contrasts controls the noncoverage error rate at
#' α for each contrast in the set, thereby producing a familywise error
#' rate which is greater than α (see Bird, 2002, bottom of page 204).
#'
#' bf - bonferonni t ci's - only valid if contrasts are defined independently
#' of the data. Controls the familywise non-coverage error rate at alpha, given
#' distributional assumptions are met. (see Bird, 2002, pg. 205)
#'
#' ph - post-hoc ci's - valid for post-hoc contrasts, will control the
#' familywise non-coverage error rate at alpha, given distributional assumptions
#' are met (see Bird, 2002, pg. 217, eqs. 7-9).
#'
#' @param model an anova model made using the afex package (class afex_aov)
#' @param contrast_tables An original `emmGrid`, or a list of original
#' `emmGrid` contrast tables generated by [emmeans::contrast()]. PsyR requires
#' the retained coefficient information to remove non-contrast rows and assess
#' cross-table orthogonality; already summarised `summary_emm` inputs are not
#' accepted. If there is only one table, it need not be wrapped in a list.
#' @param method a single string - method for confidence interval computation -
#' "ind", "bf", "ph", or "smr" - see further details below
#' @param family_list Optional list containing one family code per contrast
#' table: `"b"`, `"w"`, or `"bw"`. The default, `NULL`, infers each family
#' from the `afex_aov` model and the coefficients retained by the original
#' `emmGrid`. An explicit value is retained as a compatibility fallback and is
#' checked against the inferred family whenever inference is possible.
#' @param between_factors Optional list of between-subject factor names. PsyR
#' normally infers the relevant factors separately for every contrast table.
#' This argument is a fallback for an explicitly declared family that cannot be
#' inferred from its contrast table.
#' @param within_factors Optional list of within-subject factor names. PsyR
#' normally infers the relevant factors separately for every contrast table.
#' This argument is a fallback for an explicitly declared family that cannot be
#' inferred from its contrast table.
#' @param alpha - desired type 1 error rate. Either a single value (e.g. alpha = .05)
#' that will be applied to each family, or a list of alphas of length
#' contrast_tables. Assumes that the alphas are provided in the order as should be
#' applied to contrast_tables. default = .05.
#' @param independent - a boolean value, default = TRUE. If TRUE, correction will
#' be applied to each family independently. If FALSE, all contrasts will be summed
#' together and treated as one family for the purposes of correction.
#' This is only relevant if method = "bf" or method = "ph", and will be ignored if method = "ind".
#' For Bonferroni intervals, `family_group` takes precedence when supplied.
#' @param family_group Optional atomic vector containing one group identifier per
#' contrast table. For `method = "bf"`, tables with the same identifier share one
#' Bonferroni correction after non-contrast rows have been removed. When supplied,
#' this grouping takes precedence over `independent`. All tables in a group must
#' use the same `alpha`. Other methods currently reject this argument.
#' @param nu1 - if independent is set to FALSE, and method = "ph", then supply nu1 (df1) that
#' is used to adjust the critical constant to control for type 1 error (see eqs 7, 8, 9 of
#' Bird (2002) https://doi.org/10.1177/0013164402062002001). default = NA
#' @param smr_params - a list of parameters required for the smr method.
#' This should contain the following fields: p, q, n_sim (optional, default = 100000),
#' and seed (optional, default = NULL). See Bird & Hazli-Pavlovic (2005)
#' https://doi.org/10.1111/j.1467-9280.2005.01587.x Table 2, for the definition of p and q,
#' and the documentation for the smr method (?smr_crit) for further details on n_sim and seed.
#' default = NULL
#' @param seed Optional random seed for the SMR simulation. This top-level
#'   argument is retained as a convenience; `smr_params$seed` takes precedence
#'   when both are supplied. It is ignored for non-SMR methods.
#' @param family_check How to handle family mismatches or unverifiable tables:
#' `"error"`, `"warn"`, or `"none"`. The check distinguishes between-, within-,
#' and between-by-within tables but does not judge the validity of the contrast
#' coefficients. Automatic inference always requires an original `emmGrid` and
#' never guesses when the family is mixed or unknown.
#' For independent post-hoc intervals, the same setting controls how an
#' unresolved participating-factor dimension is handled because that dimension
#' determines the post-hoc critical constant.
#' @param family_check_tol Numeric relative tolerance used when detecting
#' factor participation, deciding whether coefficient rows sum to zero, and
#' assessing cross-table orthogonality.
#' @return A list of `emmeans` contrast tables with confidence intervals added.
#'   Each table retains the original `emmeans` `p.value` column and adds
#'   `psyr_p_value`, the contrast-specific p-value computed from the same PsyR
#'   reference distribution as its confidence interval. The table's
#'   `psyr_p_value_method` attribute records the method used for the PsyR
#'   p-values. Non-contrast rows are removed before correction. The attributes
#'   `psyr_dropped_noncontrasts`, `psyr_orthogonality`, and
#'   `psyr_family_group` and `psyr_family_size` record filtering and
#'   grouping diagnostics, while
#'   `mesg` contains corresponding human-readable messages.
#' @export
#'
#' @examples
#' data(spacing)
#' # fit model
#' mod <- afex::aov_ez("subj","yield", spacing, within = "spacing", between = "group")
#' sum_emm_btwn <- emmeans::emmeans(mod, "group") # get marginal means
#' con <- list( # define some contrasts
#'             "12vs34" = c(0.5, 0.5, -0.5, -0.5),
#'              "1vs2" = c(1, -1, 0, 0),
#'              "3vs4" = c(0, 0, 1, -1)
#'              )
#' btwn_con <- emmeans::contrast(sum_emm_btwn, con) # get contrast table
#' # now add CI's using post-hoc method
#' psyci(model = mod, contrast_tables = list(btwn_con), method = "ph")
psyci <- function(model, contrast_tables, method,
                  family_list = NULL,
                  between_factors = NA,
                  within_factors = NA,
                  alpha = 0.05,
                  independent = TRUE,
                  family_group = NULL,
                  nu1 = NA,
                  smr_params = NULL,
                  seed = NULL,
                  family_check = c("error", "warn", "none"),
                  family_check_tol = sqrt(.Machine$double.eps)){

  if(!inherits(model, "afex_aov")){
    stop("Error: model needs to be of class afex_aov")
  }
  if (!method %in% c("ind", "bf", "ph", "smr")){
    stop("Error: method should be ind, bf, ph, or smr")
  }

  # first check if a single contrast table has been entered, and if so, convert
  # to be a list
  types <- c("emmGrid", "summary_emm")
  if (sum(sapply(types, inherits, x=contrast_tables))){
    # if this is passed, then someone has entered a single object rather than a
    # list
    contrast_tables <- list(contrast_tables) # convert to list
  }
  test_emmGrids <- sum(sapply(contrast_tables, inherits, "emmGrid"))
  test_summary_emm <- sum(sapply(contrast_tables, inherits, "summary_emm"))
  if (test_emmGrids == length(contrast_tables) |
      test_summary_emm == length(contrast_tables)){
  } else {
    stop("Error: contrast table needs to be of class emmGrid or summary_emm")
  }
  if (test_summary_emm > 0L) {
    stop(
      paste0(
        "PsyR requires original emmGrid objects to identify genuine contrasts ",
        "and assess orthogonality. Pass the original emmeans contrast objects, ",
        "not summary_emm tables."
      ),
      call. = FALSE
    )
  }
  family_group <- .validate_family_group(
    family_group,
    n_tables = length(contrast_tables),
    method = method
  )

  family_check <- match.arg(family_check)
  family_report <- check_contrast_families(
    model = model,
    contrast_tables = contrast_tables,
    family_list = family_list,
    between_factors = between_factors,
    within_factors = within_factors,
    mode = family_check,
    tol = family_check_tol
  )
  if (anyNA(family_report$families) ||
      !all(family_report$families %in% c("b", "w", "bw"))) {
    stop(
      paste0(
        "PsyR cannot select critical constants until every contrast table ",
        "has one resolved family. Supply original emmGrid objects, split ",
        "mixed-family tables, or provide family_list explicitly."
      ),
      call. = FALSE
    )
  }
  family_list <- as.list(family_report$families)

  fallback_between <- family_report$factor_arguments$between
  fallback_within <- family_report$factor_arguments$within
  between_factor_sets <- lapply(family_report$tables, function(table) {
    if (length(table$between_factors) > 0L) {
      table$between_factors
    } else {
      fallback_between
    }
  })
  within_factor_sets <- lapply(family_report$tables, function(table) {
    if (length(table$within_factors) > 0L) {
      table$within_factors
    } else {
      fallback_within
    }
  })

  contrast_preparation <- .prepare_psyci_contrast_tables(
    contrast_tables = contrast_tables,
    family_report = family_report,
    tol = family_check_tol
  )
  contrast_tables <- contrast_preparation$tables
  correction_groups <- if (method == "bf") {
    if (!is.null(family_group)) {
      family_group
    } else if (independent) {
      paste0("table_", seq_along(contrast_tables))
    } else {
      rep("pooled", length(contrast_tables))
    }
  } else {
    rep(NA_character_, length(contrast_tables))
  }
  .warn_separate_nonorthogonal_tables(
    orthogonality = contrast_preparation$orthogonality,
    correction_groups = correction_groups,
    method = method,
    independent = independent
  )

  if (method %in% "ph" && independent) {
    family_codes <- unlist(family_list, use.names = FALSE)
    missing_between <- which(
      family_codes %in% c("b", "bw") &
        lengths(between_factor_sets) == 0L
    )
    if (length(missing_between) > 0L) {
      stop(
        paste0(
          "PsyR could not determine the between-subject factors required for ",
          "independent post-hoc table(s): ",
          paste(missing_between, collapse = ", "),
          ". Supply original emmGrid objects or `between_factors`."
        )
      )
    }
    missing_within <- which(
      family_codes %in% c("w", "bw") &
        lengths(within_factor_sets) == 0L
    )
    if (length(missing_within) > 0L) {
      stop(
        paste0(
          "PsyR could not determine the within-subject factors required for ",
          "independent post-hoc table(s): ",
          paste(missing_within, collapse = ", "),
          ". Supply original emmGrid objects or `within_factors`."
        )
      )
    }

    unresolved_ph <- unlist(lapply(
      seq_along(family_report$tables),
      function(index) {
        table_report <- family_report$tables[[index]]
        contrast_report <- table_report$contrasts
        if (nrow(contrast_report) == 0L) {
          return(character())
        }
        unresolved <- which(
          contrast_report$detected_family %in% c("b", "w", "bw") &
            contrast_report$scope == "unknown"
        )
        if (length(unresolved) == 0L) {
          return(character())
        }

        vapply(unresolved, function(row) {
          participation <- if (length(table_report$participation) >= row) {
            table_report$participation[[row]]
          } else {
            NULL
          }
          unresolved_factors <- unique(c(
            participation$missing_context,
            participation$ambiguous_context
          ))
          factor_text <- if (length(unresolved_factors) > 0L) {
            paste0("; unresolved factors: ", paste(
              unresolved_factors,
              collapse = ", "
            ))
          } else {
            ""
          }
          sprintf(
            "%s, contrast '%s'%s",
            family_report$summary$table[[index]],
            contrast_report$label[[row]],
            factor_text
          )
        }, character(1))
      }
    ), use.names = FALSE)
    if (length(unresolved_ph) > 0L && family_check != "none") {
      scope_message <- paste0(
        "PsyR could not verify the participating-factor dimension required ",
        "for independent post-hoc critical constants: ",
        paste(unresolved_ph, collapse = "; "),
        ". Supply an emmeans contrast with unambiguous factor participation, ",
        "or use `family_check = \"warn\"` or `family_check = \"none\"` only ",
        "when the supplied factor lists intentionally define the dimension."
      )
      if (family_check == "error") {
        stop(scope_message, call. = FALSE)
      }
      warning(scope_message, call. = FALSE)
    }
  }

  if (!independent){
    if (method %in% "ph"){
      if (is.na(nu1)) {
        stop("Error: post-hoc method with non-orthogonal families requested but nu1 remains undefined. Please supply via `nu1=` argument")
      }
    }
  }

  if (method %in% "smr"){

    # double check families to make sure no within sub factors
    fam_check <- unlist(
      lapply(family_list, function(x) x %in% c("w", "bw")))

    if (any(unlist(fam_check))){
      stop("Error: You have requested the SMR procedure, but the family_list contains within subject related families.
           Please check your family_list and method arguments.")
    }

    # now check that smr_params has been entered correctly
    # first pass
    if (any(is.na(smr_params))){
      stop("Error: You have requested the SMR procedure,
           but have not supplied the required smr_params argument.
           Please check your method and smr_params arguments.")
    }
    # checking for fields, and the length of those fields
    required_fields = c("p", "q")
     if (!all(required_fields %in% names(smr_params))){
       stop("Error: You have requested the SMR procedure, but your smr_params argument is missing one or more required fields.
            Please check your method and smr_params arguments.")
     }
  }
  # if method is smr, check whether or not the n_sim or seed params
  # have been passed in. If not, set to the defaults
  if (method %in% "smr"){
    if (!"n_sim" %in% names(smr_params)){
      smr_params$n_sim = 100000
    }
    if (!"seed" %in% names(smr_params) && !is.null(seed)) {
      smr_params$seed = seed
    }
  }
  # if the method is not smr, then set an smr_params value to null,
  # for later use in the update_attributes function
  if (!method %in% "smr"){
   smr_params = NULL
  }

  # now put the contrast table info together
  contrast_info <- do.call(rbind, contrast_tables)
  all_contrast_tables <- summary(contrast_info) # create one big contrast table that one can index easily
  contrast_tables <- contrast_tables # keeping list
  # get the error df
  # Non-estimable rows have missing degrees of freedom. They should receive
  # missing intervals and p-values without preventing estimable rows in the
  # same table from being processed.
  v_e = unique(all_contrast_tables$df[!is.na(all_contrast_tables$df)])

  if (length(v_e) == 0){
    stop("Error: no estimable contrasts with an error df were provided")
  }
  if (length(v_e) > 1){
    stop("Error: more than one contrast analysis passed in")
  }

  if (method %in% "smr") {
    smr_params <- .validate_smr_p_value_params(smr_params, v_e)
  }

  # Post-hoc dimensions are table-specific because different contrast tables
  # may involve different subsets of the model factors.
  v_bs = rep(list(NA_real_), length(contrast_tables))
  v_ws = rep(list(NA_real_), length(contrast_tables))
  nk = rep(NA_integer_, length(contrast_tables))
  smr_distribution = NULL

  if (method %in% "ph"){
    for (index in seq_along(contrast_tables)) {
      family <- family_list[[index]]
      if (family %in% c("b", "bw")) {
        v_bs[[index]] <- if (independent) {
          compute_df(model, fctrs = as.list(between_factor_sets[[index]]))
        } else {
          nu1
        }
      }
      if (family %in% c("w", "bw")) {
        v_ws[[index]] <- if (independent) {
          compute_df(model, fctrs = as.list(within_factor_sets[[index]]))
        } else {
          nu1
        }
      }
    }
  }

  # now get the appropriate critical constant, given requested
  # method
  # first, make a list for critical constants, that is as long
  # as the number of contrast tables that have been passed in as
  # contrast tables
  # now make sure provided alphas are compatible with the number of families
  if (length(alpha) == 1){
    alphas = rep(list(alpha), length(contrast_tables))
  } else {
    alphas = alpha
  }
  if (length(alphas) != length(contrast_tables)){
    stop(sprintf("Error! Provided alpha is of length > 1 and does not match
                   length of contrast tables"))
  }
  names(alphas) = unlist(family_list, use.names = FALSE)

  if (method %in% "ind"){

    critical_constant = lapply(alphas, cc_ind_t, v_e=v_e)

  } else if (method %in% "bf") {

    # Count only genuine contrasts and pool tables according to their group.
    nk = .bonferroni_group_sizes(
      counts = contrast_preparation$counts,
      groups = correction_groups,
      alphas = alphas
    )

   critical_constant = mapply(cc_bonf_t, n_k=nk, alpha=alphas, MoreArgs=list(v_e=v_e), SIMPLIFY=FALSE)

  } else if (method %in% "ph"){
    critical_constant = Map(
      function(alpha_value, family, v_b, v_w) {
        if (family == "b") {
          cc_ph_b(v_b = v_b, v_e = v_e, alpha = alpha_value)
        } else if (family == "w") {
          cc_ph_w(v_w = v_w, v_e = v_e, alpha = alpha_value)
        } else {
          cc_ph_bw(
            v_w = v_w,
            v_b = v_b,
            v_e = v_e,
            alpha = alpha_value
          )
        }
      },
      alphas,
      family_list,
      v_bs,
      v_ws
    )
    names(critical_constant) = unlist(family_list, use.names = FALSE)
  } else if (method %in% "smr"){

    # do we have a seed setting?
    if ("seed" %in% names(smr_params)){
      seed = smr_params$seed
    } else {
      seed = NULL
    }
    # Fit one reference distribution for both the confidence intervals and
    # p-values. This avoids repeated simulations and keeps the two outputs
    # based on exactly the same approximation.
    smr_alpha <- unlist(unique(alphas))
    if (length(smr_alpha) > 1){
      stop("Error: more than one alpha value provided for SMR method")
    }
    smr_distribution = .fit_smr_reference_distribution(
      p = smr_params$p,
      q = smr_params$q,
      n = v_e,
      n_sim = smr_params$n_sim,
      seed = seed
    )
    cc_smr = sqrt(.smr_reference_quantile(smr_alpha, smr_distribution))
    critical_constant = rep(cc_smr, length(contrast_tables))
  }

  # now get SE from each contrast table in contrast_tables, compute CIs using appropriate
  # cc, and save results to a concatenated summary table
  contrasts_w_cis <- mapply(get_cis, contrast_tables, critical_constant, SIMPLIFY=FALSE)

  # Add the PsyR-compatible p-value without replacing the original emmeans
  # p.value column. For SMR, reuse the distribution fitted above.
  p_value_nk <- if (method %in% "bf") {
    as.list(nk)
  } else {
    rep(list(NULL), length(contrast_tables))
  }
  contrasts_w_cis <- Map(
    function(contrast_table, family, n_k, v_b, v_w) {
      if (method %in% "smr") {
        statistic <- (contrast_table$estimate / contrast_table$SE)^2
        p_value <- .smr_reference_p_value(statistic, smr_distribution)
        if (any(!is.na(statistic) & !is.finite(p_value))) {
          stop(
            paste(
              "The SMR reference distribution produced a non-finite",
              "p-value for the supplied contrasts."
            ),
            call. = FALSE
          )
        }
        p_value <- pmin(1, pmax(0, p_value))
      } else {
        p_value <- compute_contrast_p_value(
          estimate = contrast_table$estimate,
          se_contrast = contrast_table$SE,
          method = method,
          v_e = v_e,
          family = if (method %in% "ph") family else NULL,
          n_k = if (method %in% "bf") n_k else NULL,
          v_b = if (
            method %in% "ph" && family %in% c("b", "bw")
          ) v_b else NULL,
          v_w = if (
            method %in% "ph" && family %in% c("w", "bw")
          ) v_w else NULL
        )
      }
      contrast_table[["psyr_p_value"]] <- unname(p_value)
      contrast_table
    },
    contrasts_w_cis,
    family_list,
    p_value_nk,
    v_bs,
    v_ws
  )

  # now I want to add information about what happened as an attribute to the
  # list of contrast tables
  n_c_tables = length(contrast_tables)
  methods = as.list(rep(method, n_c_tables))
  families = family_list
  btwn_fctrs = Map(function(family, factors) {
    if (family %in% c("b", "bw")) factors else NA
  }, families, between_factor_sets)
  wthn_fctrs = Map(function(family, factors) {
    if (family %in% c("w", "bw")) factors else NA
  }, families, within_factor_sets)
  v_es = as.list(rep(v_e, n_c_tables))
  alphas = alphas

  contrasts_w_cis <- mapply(update_attributes, contrasts_w_cis, method = methods,
                            p_value_method = methods,
                            family=families, between_factors=btwn_fctrs,
                            within_factors=wthn_fctrs, v_b=v_bs, v_w=v_ws,
                            v_e=v_es, alpha=alphas,
                            MoreArgs=list(smr_params=smr_params),
                            SIMPLIFY = FALSE)

  diagnostic_family_sizes <- if (method == "bf") {
    as.list(nk)
  } else {
    rep(list(NA_integer_), length(contrasts_w_cis))
  }
  contrasts_w_cis <- Map(
    function(result, index, correction_group, family_size) {
      .attach_psyci_contrast_diagnostics(
        result = result,
        index = index,
        preparation = contrast_preparation,
        correction_group = correction_group,
        family_size = family_size
      )
    },
    contrasts_w_cis,
    seq_along(contrasts_w_cis),
    as.list(correction_groups),
    diagnostic_family_sizes
  )

  names(contrasts_w_cis) = unlist(families, use.names = FALSE)

  return(contrasts_w_cis)
}
